FROM centos:7

RUN yum -y install gcc && \
    yum -y install gcc-c++ && \
    yum -y install cmake && \
    yum -y install make && \
    yum -y install vim && \
    yum -y install wget

RUN yum clean all

RUN mkdir -p /source/api/ /source/code/ && cd /source/api && wget https://products.solace.com/download/C_API_LINUX64 && tar xvf C_API_LINUX64 --strip-components=1 && rm C_API_LINUX64
ENV SOLACE_API_DIR /source/api/
WORKDIR /source/code/

CMD ["/bin/bash"]
