FROM centos:7

RUN yum -y install gcc && \
    yum -y install gcc-c++ && \
    yum -y install cmake && \
    yum -y install make && \
    yum -y install vim 

RUN yum clean all

RUN mkdir -p /source/api/ /source/code/

ADD solaceapi.tar.gz /source/api/
ENV SOLACE_API /source/api/
WORKDIR /source/code/

CMD ["/bin/bash"]
