FROM centos:7

COPY q /usr/local/q
ENV QHOME /usr/local/q
ENV PATH /usr/local/q/l64:$PATH

ADD solaceapi.tar.gz /usr/local/solaceapi/
COPY examples /usr/local/solace
ENV LD_LIBRARY_PATH /usr/local/solaceapi/lib/:$LD_LIBRARY_PATH

COPY libdeltasolace.so /usr/local/q/l64/
WORKDIR /usr/local/solace/
CMD ["/bin/bash"]
